[workspace]
members = [
	"sstat",
	"sstatc"
]

default-members = [
	"sstat",
	"sstatc"
]

exclude = [
	"target",
	"docs",
]

[profile.release]
opt-level = 3
lto = "thin"
strip = true
codegen-units = 1
